; Various useful ASCII character codes

ASCII_NUL = $00 ; null
ASCII_SOH = $01 ; start of heading
ASCII_EOT = $04 ; end of transmission
ASCII_ACK = $06 ; +ve acknowledge
ASCII_BEL = $07 ; bell
ASCII_BS  = $08	; back space
ASCII_LF  = $0A	; line feed
ASCII_CR  = $0D	; carriage return
ASCII_NAK = $15 ; -ve acknowledge
ASCII_CAN = $18 ; cancel
ASCII_ESC = $1B	; escape
ASCII_DEL = $7F ; delete

; vi:ft=asm
